package Crypto;
import java.io.UnsupportedEncodingException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Random;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.ShortBufferException;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;

/**
 * The Crypto class encapsulated a set of procedures for Encrypting/Decrypting
 * with AES as well as generating arbitrary size Initilization vectors.
 * 
 * @author Philip Gebhardt
 * @version Fall 2012, CS158B
 */
public class Crypto
{
    /**
     * Encrypts a given byte stream using the AES cipher, CBC mode, and
     * PKCS5 Padding algorithms.
     * 
     * @param input - Bytes to be encrypted
     * @param key - Symmetric key to encrypt with
     * @param iv - Initialization vector
     * @return encrypted byte stream
     * @throws NoSuchAlgorithmException
     * @throws NoSuchPaddingException
     * @throws InvalidKeyException
     * @throws InvalidAlgorithmParameterException
     * @throws ShortBufferException
     * @throws IllegalBlockSizeException
     * @throws BadPaddingException
     * @throws UnsupportedEncodingException
     */
    public static byte[] AESCBCencrypt(byte[] input, Key key, byte[] iv)
            throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, InvalidAlgorithmParameterException,
            ShortBufferException, IllegalBlockSizeException, BadPaddingException, UnsupportedEncodingException
    {
        int ciphertext_len;
        byte[] keyBytes, ciphertext;
        SecretKeySpec keySpec;
        IvParameterSpec ivSpec;
        Cipher cipher;
        
        keyBytes = key.getBytes();
        keySpec = new SecretKeySpec(keyBytes, "AES");
        ivSpec = new IvParameterSpec(iv);
        cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipher.init(Cipher.ENCRYPT_MODE, keySpec, ivSpec);
        ciphertext = new byte[cipher.getOutputSize(input.length)];
        
        ciphertext_len = cipher.update(input, 0, input.length, ciphertext, 0);
        ciphertext_len += cipher.doFinal(ciphertext, ciphertext_len);
        return ciphertext;
    }
    
    /**
     * Decrypts a given byte stream using the AES cipher, CBC mode, and
     * PKCS5 Padding algorithms.
     * 
     * @param input - Bytes to be decrypted
     * @param key - Symmetric key to decrypt
     * @param iv - Initialization vector
     * @return decrypted byte stream
     * @throws NoSuchAlgorithmException
     * @throws NoSuchPaddingException
     * @throws InvalidKeyException
     * @throws InvalidAlgorithmParameterException
     * @throws ShortBufferException
     * @throws IllegalBlockSizeException
     * @throws BadPaddingException
     * @throws UnsupportedEncodingException
     */
    public static byte[] AESCBCdecrypt(byte[] input, Key key, byte[] iv)
    		throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, InvalidAlgorithmParameterException,
    		ShortBufferException, IllegalBlockSizeException, BadPaddingException, UnsupportedEncodingException
    {
        int plaintext_len;
        byte[] keyBytes, plaintext;
        SecretKeySpec keySpec;
        IvParameterSpec ivSpec;
        Cipher cipher;

        keyBytes = key.getBytes();
        keySpec = new SecretKeySpec(keyBytes, "AES");
        ivSpec = new IvParameterSpec(iv);
        cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, keySpec, ivSpec);
        plaintext = new byte[cipher.getOutputSize(input.length)];
        
        plaintext_len = cipher.update(input, 0, input.length, plaintext, 0);
        plaintext_len += cipher.doFinal(plaintext, plaintext_len);
        return plaintext;
    }
    
    /**
     * Generates a byte stream that can be used as an initialization vector
     * @param seed - Seed of randomness
     * @param byteLength - Byte length of the stream
     * @return Byte array randomly generated by seed
     */
    public static byte[] generateIV(int seed, int byteLength)
    {
    	byte[] iv = new byte[byteLength];
    	Random random = new Random(seed);
    	random.nextBytes(iv);
    	return iv;
    }
}
